#!/bin/sh
#
#

topdir=$(pwd)
echo $topdir
#run the services

cd $topdir/addison/tracks
go run main.go &
TRACKS=$(echo $!)
cd $topdir/addison/search
go run main.go &
SEARCH=$(echo $!)
cd $topdir/addison/cooltown
go run main.go &
COOLTOWN=$(echo $!)

# wait for each process to start
sleep 3

# run the tests in the tracks microservice

cd $topdir/addison/tracks/
echo -e "running test 1 : inserting to database"
./script1.sh
echo -e "running test 2 : getting single track from database"
./script2.sh
echo -e "running test 3 : getting all tracks from database"
./script3.sh
echo -e "running test 4 : deleting track from database"
./script4.sh
echo -e "running test 2 : getting track after it has been deleted from database"
./script2.sh
echo -e "putting track back into database"
./script1.sh

# run the tests in the search microservice

echo -e ""

cd $topdir/addison/search
echo -e "running test 5 : testing search with backstreets back"
./script5.sh

# run the tests in the cooltown microservice

echo -e "n"

cd $topdir/addison/cooltown
echo -e "running test 6 : testing cooltown with backstreets back"
./script6.sh

# shutdown the microservices
kill $TRACKS
kill $SEARCH
kill $COOLTOWN
